export const deptSeoul = [
  { name: "Business & AI 전공", code: "A4AB2" },
  { name: "ELLT학과", code: "A1CG1" },
  { name: "EU전공", code: "AAQ01" },
  { name: "FATI전공", code: "AAMB1" },
  { name: "KFL학부", code: "A5A" },
  { name: "Language & AI융합전공", code: "A0A01" },
  { name: "Language & Diplomacy전공", code: "AKAA1" },
  { name: "Language & Diplomacy학부", code: "AKA" },
  { name: "Language & Trade전공", code: "A2AA1" },
  { name: "Language & Trade학부", code: "A2A" },
  { name: "Social Science & AI융합전공", code: "A0B01" },
  { name: "경영학전공", code: "ALAA1" },
  { name: "경제학부", code: "AEC" },
  { name: "경제학전공", code: "AECA1" },
  { name: "광고·PR·브랜딩전공", code: "ACDD1" },
  { name: "교육학", code: "AFF01" },
  { name: "국가리더전공", code: "ACAI1" },
  { name: "국제통상학과", code: "AEAA1" },
  { name: "국제학부", code: "AGA" },
  { name: "국제학전공", code: "AGAA1" },
  { name: "네덜란드어과", code: "AAH01" },
  { name: "노어과", code: "AAD01" },
  { name: "독일어과", code: "AAC01" },
  { name: "동북아외교통상전공", code: "ABP02" },
  { name: "말레이.인도네시아어과", code: "ABC01" },
  { name: "몽골어과", code: "ABJ01" },
  { name: "문화콘텐츠학전공", code: "ANDD2" },
  { name: "미디어커뮤니케이션학부", code: "ACD" },
  { name: "방송·영상·뉴미디어전공", code: "ACDE1" },
  { name: "베트남어과", code: "ABF01" },
  { name: "브릭스전공", code: "AAP01" },
  { name: "사학과", code: "ANDB2" },
  { name: "상담·UX심리전공", code: "A4A04" },
  { name: "세계문화예술경영전공", code: "AANA1" },
  { name: "스칸디나비아어과", code: "AAI01" },
  { name: "스페인어과", code: "AAE01" },
  { name: "아랍어과", code: "ABD01" },
  { name: "언론·정보전공", code: "ACDA1" },
  { name: "언어인지과학과", code: "ANDC2" },
  { name: "영미문학·문화학과", code: "A1CD1" },
  { name: "영어교육과", code: "AFA01" },
  { name: "영어통번역학과", code: "A1CE1" },
  { name: "외국어교육학부(독일어교육전공)", code: "AFJ02" },
  { name: "외국어교육학부(중국어교육전공)", code: "AFJ03" },
  { name: "외국어교육학부(프랑스어교육전공)", code: "AFJ01" },
  { name: "외국어로서의한국어교육전공", code: "A5A01" },
  { name: "외국어로서의한국어통번역전공", code: "A5A02" },
  { name: "융복합소프트웨어전공", code: "A4AB1" },
  { name: "융합일본지역전공", code: "AJDA1" },
  { name: "융합일본지역학부", code: "AJD" },
  { name: "이탈리아어과", code: "AAF01" },
  { name: "인도어과", code: "ABG01" },
  { name: "일본언어문화전공", code: "AJCA1" },
  { name: "일본언어문화학부", code: "AJC" },
  { name: "정치외교학과", code: "ACBA1" },
  { name: "중국언어문화전공", code: "AICA1" },
  { name: "중국언어문화학부", code: "AIC" },
  { name: "중국외교통상전공", code: "AIDA1" },
  { name: "중국외교통상학부", code: "AID" },
  { name: "차이나데이터큐레이션전공", code: "AICA2" },
  { name: "철학과", code: "ANDA2" },
  { name: "태국학과", code: "ABE01" },
  { name: "튀르키예·아제르바이잔학과", code: "ABH11" },
  { name: "페르시아어·이란학과", code: "ABI01" },
  { name: "포르투갈어과", code: "AAK01" },
  { name: "프랑스·EU전공", code: "AAMC1" },
  { name: "프랑스어학부", code: "AAM" },
  { name: "프랑스응용어문학전공", code: "AAMA1" },
  { name: "한국어교육과", code: "AFD01" },
  { name: "행정학과", code: "ACBB1" }
];

export const deptGlobal = [
 { name: "AI데이터융합전공", code: "A9A01" },
  { name: "AI융합전공(Software&AI)", code: "A4BA3" },
  { name: "Business & AI 전공", code: "A4BB1" },
  { name: "Finance & AI융합전공", code: "A9B01" },
  { name: "Global Business & Technology전공", code: "ARDA1" },
  { name: "ICT&AI세부모듈", code: "A6A92" },
  { name: "TESOL영어학전공", code: "AO1D2" },
  { name: "게임한류문화산업세부모듈", code: "A6A90" },
  { name: "공과대학(공통)", code: "ATZ" },
  { name: "광고·PR·브랜딩전공", code: "ACDD1" },
  { name: "교육학", code: "AFF01" },
  { name: "국가리더전공(글로벌)", code: "ACAH1" },
  { name: "국제금융학과", code: "ARCA1" },
  { name: "그리스‧불가리아학과", code: "APH02" },
  { name: "글로벌e스포츠매니지먼트전공", code: "AXB03" },
  { name: "글로벌스포츠산업전공", code: "AXB02" },
  { name: "글로벌스포츠산업학부", code: "AXB" },
  { name: "기후변화융합전공", code: "AMAA1" },
  { name: "남아프리카어전공", code: "APK03" },
  { name: "독일어통번역학과", code: "AOC02" },
  { name: "동아프리카어전공", code: "APK01" },
  { name: "디지털콘텐츠학부", code: "AXC" },
  { name: "러시아학과", code: "AQJ02" },
  { name: "루마니아학과", code: "APC02" },
  { name: "말레이.인도네시아어통번역학과", code: "AORI2" },
  { name: "문화콘텐츠학전공", code: "ANDD2" },
  { name: "미국․영연방전략세부모듈", code: "A6A84" },
  { name: "바이오메디컬공학전공", code: "AYAA1" },
  { name: "반도체전자공학부(반도체공학전공)", code: "ATN" },
  { name: "반도체전자공학부(전자공학전공)", code: "ATO" },
  { name: "방송·영상·뉴미디어전공", code: "ACDE1" },
  { name: "브라질학과", code: "AQ202" },
  { name: "사학과", code: "ANDB2" },
  { name: "산업경영공학과", code: "ATB02" },
  { name: "생명공학과", code: "ASJB2" },
  { name: "서아프리카어전공", code: "APK02" },
  { name: "세계문화예술경영전공", code: "AOSA1" },
  { name: "세르비아·크로아티아학과", code: "APF02" },
  { name: "수학과", code: "ASHA2" },
  { name: "스페인어통번역학과", code: "AOD02" },
  { name: "아랍어통번역세부모듈", code: "A6A82" },
  { name: "아랍어통번역학과", code: "AORG2" },
  { name: "아프리카학부", code: "APK" },
  { name: "언론·정보전공", code: "ACDA1" },
  { name: "언어인지과학과", code: "ANDC2" },
  { name: "영미문학·번역전공", code: "AO1C2" },
  { name: "영어통번역세부모듈", code: "A6A81" },
  { name: "영어통번역학부", code: "AO1" },
  { name: "영어통번역학전공", code: "AO1A2" },
  { name: "우크라이나학과", code: "APG02" },
  { name: "융합비즈니스세부모듈", code: "A6A91" },
  { name: "융합인재학부", code: "A6A" },
  { name: "이탈리아․EU전략세부모듈", code: "A6A85" },
  { name: "이탈리아어통번역학과", code: "AOE02" },
  { name: "인도학과", code: "AQF02" },
  { name: "일본어통번역학과", code: "AORB2" },
  { name: "전자물리학과", code: "ASIB2" },
  { name: "정보통신공학과", code: "ATFB2" },
  { name: "정치외교학과", code: "ACBA1" },
  { name: "중국어통번역세부모듈", code: "A6A83" },
  { name: "중국어통번역학과", code: "AORA2" },
  { name: "중동․이슬람전략세부모듈", code: "A6A86" },
  { name: "중앙아시아학과", code: "API02" },
  { name: "중화권전략세부모듈", code: "A6A87" },
  { name: "철학과", code: "ANDA2" },
  { name: "체코·슬로바키아학과", code: "APD02" },
  { name: "컴퓨터공학전공", code: "ATJA1" },
  { name: "태국어통번역학과", code: "AORE2" },
  { name: "테크노미디어디자인세부모듈", code: "A6A88" },
  { name: "통계학과", code: "ASHB2" },
  { name: "투어리즘 & 웰니스학부", code: "AXD" },
  { name: "패션관광문화산업세부모듈", code: "A6A89" },
  { name: "폴란드학과", code: "APB02" },
  { name: "프랑스학과", code: "AQ102" },
  { name: "한국학과", code: "APJ02" },
  { name: "행정학과", code: "ACBB1" },
  { name: "헝가리학과", code: "APE02" },
  { name: "화학과", code: "ASJC2" },
  { name: "환경학과", code: "ASJA2" }
];

export const liberalSeoul = [
{ name: "대학외국어", code: "305" },
  { name: "미네르바인문", code: "306" },
  { name: "AI·SW·데이터", code: "30B" },
  { name: "역사와철학", code: "332" },
  { name: "과학과기술", code: "334" },
  { name: "문학과예술", code: "337" },
  { name: "사회와문화", code: "338" },
  { name: "신입생세미나", code: "350" },
  { name: "HUFS CAREER", code: "351" },
  { name: "생활과스포츠", code: "358" },
  { name: "취창업", code: "359" },
  { name: "세계시민역량", code: "35A" },
  { name: "전공탐색세미나", code: "35C" },
  { name: "외국인을위한한국학", code: "361" },
  { name: "군사학", code: "61" }
];

export const liberalGlobal = [
{ name: "대학외국어", code: "305" },
  { name: "미네르바인문", code: "306" },
  { name: "AI·SW·데이터", code: "30B" },
  { name: "역사와철학", code: "332" },
  { name: "과학과기술", code: "334" },
  { name: "문학과예술", code: "337" },
  { name: "사회와문화", code: "338" },
  { name: "신입생세미나", code: "350" },
  { name: "HUFS CAREER", code: "351" },
  { name: "생활과스포츠", code: "358" },
  { name: "취창업", code: "359" },
  { name: "세계시민역량", code: "35A" },
  { name: "전공탐색세미나", code: "35C" },
  { name: "외국인을위한한국학", code: "361" },
  { name: "마이크로디그리(영어)", code: "362" },
  { name: "군사학", code: "61" }
];

export const basicSeoul = [
 { name: "영어대학", code: "710" },
  { name: "아시아언어문화대학(특수외국어(인도.아세안지역)계열)", code: "713" },
  { name: "아시아언어문화대학(특수외국어(중동지역)계열)", code: "714" },
  { name: "중국학대학", code: "715" },
  { name: "일본학대학", code: "716" },
  { name: "사회과학대학", code: "717" },
  { name: "상경대학", code: "718" },
  { name: "경영대학", code: "719" },
  { name: "AI융합대학", code: "71G" },
  { name: "프랑스어학부", code: "724" },
  { name: "독일어과", code: "725" },
  { name: "노어과", code: "726" },
  { name: "스페인어과", code: "727" },
  { name: "이탈리아어과", code: "728" },
  { name: "포르투갈어과", code: "729" },
  { name: "네덜란드어과", code: "72A" },
  { name: "스칸디나비아어과", code: "72B" },
  { name: "말레이·인도네시아어과", code: "72C" },
  { name: "베트남어과", code: "72E" },
  { name: "인도어과", code: "72F" },
  { name: "아랍어과", code: "72G" },
  { name: "튀르키예·아제르바이잔학과", code: "72H" },
  { name: "페르시아어·이란학과", code: "72I" },
  { name: "몽골어과", code: "72J" },
  { name: "중국언어문화학부", code: "72K" },
  { name: "중국외교통상학부", code: "72L" },
  { name: "일본언어문화학부", code: "72M" },
  { name: "융합일본지역학부", code: "72N" },
  { name: "대학기초", code: "74" }
];

export const basicGlobal = [
{ name: "인문대학", code: "71A" },
  { name: "국가전략언어대학", code: "71B" },
  { name: "경상대학", code: "71C" },
  { name: "자연과학대학", code: "71D" },
  { name: "공과대학(공과계열)", code: "71E" },
  { name: "CULTURE&TECHNOLOGY융합대학", code: "71F" },
  { name: "AI융합대학", code: "71G" },
  { name: "폴란드학과", code: "72O" },
  { name: "루마니아학과", code: "72P" },
  { name: "체코·슬로바키아학과", code: "72Q" },
  { name: "헝가리학과", code: "72R" },
  { name: "세르비아·크로아티아학과", code: "72S" },
  { name: "그리스·불가리아학과", code: "72T" },
  { name: "중앙아시아학과", code: "72U" },
  { name: "아프리카학부", code: "72V" },
  { name: "우크라이나학과", code: "72W" },
  { name: "한국학과", code: "72X" },
  { name: "이공영역", code: "734" }
];